### ISSUE TITLE
Error:  import cycle not allowed

### ISSUE THREAD

**Issue by Scylla2020** [89z/rosso#6]
Hi I'm trying to build a shared library and when I ran `go build -buildmode=c-shared -o example.so example.go` I got an error 

```
package command-line-arguments
imports github.com/89z/format/crypto
imports github.com/89z/format/crypto: import cycle not allowed
```
When I build locally it works fine though in windows. Any idea what could be causing this. Im running on linux

**Comment by 89z** [comment]
https://github.com/89z/rosso#issues
